"""update user server

Revision ID: 2d6a6948f88a
Revises: e9b16b60b8f4
Create Date: 2023-10-15 19:34:11.726118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6a6948f88a'
down_revision: Union[str, None] = 'e9b16b60b8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'image')
    # ### end Alembic commands ###
