"""add_user_server

Revision ID: a6e37b7ded46
Revises: 80a77bd85a29
Create Date: 2023-09-06 00:15:18.156768

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6e37b7ded46'
down_revision: Union[str, None] = '80a77bd85a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
                    sa.Column('openstack_id', sa.UUID(), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('openstack_id'),
                    sa.UniqueConstraint('openstack_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    # ### end Alembic commands ###
