"""add_server_config

Revision ID: be77fc22a5da
Revises: a6e37b7ded46
Create Date: 2023-09-10 14:52:33.030891

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be77fc22a5da'
down_revision: Union[str, None] = 'a6e37b7ded46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_config',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('flavor', sa.String(), nullable=False),
                    sa.Column('networks', sa.ARRAY(sa.String()), nullable=True),
                    sa.PrimaryKeyConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_config')
    # ### end Alembic commands ###
