"""insert_server_configs_and_drop_useless_tables

Revision ID: ce7d9b027314
Revises: 11a59f54d3fc
Create Date: 2023-10-10 20:42:29.666832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7d9b027314'
down_revision: Union[str, None] = '11a59f54d3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_network')
    op.drop_table('server_image')
    op.drop_table('server_flavor')
    op.create_unique_constraint(None, 'server', ['openstack_id'])

    # Insert server configs
    op.execute('''
INSERT INTO server_config VALUES
('Легка', 'Обчислювальний сервер OpenStack, сконфігурований з диском Cirros 0.6.2 x86_64 та носієм m1.medium, є ефективним вибором для задач, пов`язаних з великими даними. Cirros, відомий своєю легкістю, ідеально підходить для хмарних середовищ, забезпечуючи мінімальне споживання ресурсів для додатків Big Data. Примірник m1.medium забезпечує хороший баланс між процесором, пам`яттю та сховищем, що робить його придатним для аналізу даних, розподіленої обробки за допомогою таких інструментів, як Hadoop або Spark, а також для управління складними робочими процесами даних. Він пропонує економічно ефективний спосіб обробки великих наборів даних, використовуючи гнучкість і масштабованість OpenStack.', 'cirros-0.6.2-x86_64-disk', 'm1.medium', '{public,private}'),
('Базова', 'Обчислювальний сервер OpenStack з дистрибутивом Cirros 0.6.2 x86_64 та конфігурацією m1.tiny призначений для користувачів-початківців, які вивчають обробку великих даних. Cirros, ефективний дистрибутив Linux, розроблений для хмарних середовищ, забезпечує оптимізацію ресурсів. Хоча m1.tiny не забезпечує великих обчислювальних потужностей, це доступний варіант для тих, хто тільки починає вирішувати задачі аналізу даних в OpenStack, що робить його зручним вибором для початківців.','cirros-0.6.2-x86_64-disk', 'm1.tiny','{public,private}');
''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='unique')
    op.create_table('server_flavor',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_flavor_pkey')
    )
    op.create_table('server_image',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_image_pkey')
    )
    op.create_table('server_network',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_network_pkey')
    )
    # ### end Alembic commands ###
