"""insert_server_configs_and_drop_useless_tables

Revision ID: ce7d9b027314
Revises: 11a59f54d3fc
Create Date: 2023-10-10 20:42:29.666832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7d9b027314'
down_revision: Union[str, None] = '11a59f54d3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_network')
    op.drop_table('server_image')
    op.drop_table('server_flavor')
    op.create_unique_constraint(None, 'server', ['openstack_id'])

    # Insert server configs
    op.execute('''
INSERT INTO server_config VALUES
('Легка', 'Обчислювальний сервер OpenStack з конфігурацією диска Cirros 0.6.2 x86_64 та m1.medium - це розумний вибір для тих, хто працює з великими обсягами даних. Cirros - це легкий, ефективний дистрибутив Linux, що ідеально підходить для хмарних обчислень. Він використовує мінімум ресурсів, що робить його ідеальним для запуску додатків для роботи з великими даними без зайвих накладних витрат.

Примірник m1.medium пропонує збалансоване поєднання процесора, пам''яті та сховища, що ідеально підходить для помірних обчислювальних потреб. Ця конфігурація відмінно підходить для таких завдань, як аналіз даних, розподілена обробка за допомогою таких інструментів, як Hadoop або Spark, або управління складними робочими процесами даних. Це економічно ефективний спосіб обробляти та аналізувати великі масиви даних, насолоджуючись гнучкістю та масштабованістю OpenStack.', 'cirros-0.6.2-x86_64-disk', 'm1.medium', '{public,private}'),
('Базова', 'Обчислювальний сервер OpenStack з образом диска Cirros 0.6.2 x86_64 та конфігурацією m1.tiny є практичним вибором для користувачів, які починають працювати з великими обсягами даних. Cirros 0.6.2, відомий своєю легкістю та ефективністю, є оптимальним дистрибутивом Linux для хмарних середовищ. Він зводить споживання ресурсів до мінімуму, що робить його придатним для запуску додатків для роботи з великими даними без зайвих витрат ресурсів.

Тип екземпляра m1.tiny пропонує базове, але економічне налаштування, що робить його чудовою відправною точкою для невеликих потреб в обробці великих даних. Хоча він може не забезпечувати той самий рівень обчислювальної потужності, що й більші екземпляри, він все одно може впоратися з базовими завданнями аналізу даних і служити економічно ефективною відправною точкою для користувачів, які хочуть дослідити обробку великих даних на OpenStack. Ця комбінація пропонує практичне та бюджетне рішення для користувачів, які хочуть спробувати свої сили в обробці великих даних, використовуючи можливості хмарної інфраструктури OpenStack.','cirros-0.6.2-x86_64-disk', 'm1.tiny','{public,private}');
''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='unique')
    op.create_table('server_flavor',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_flavor_pkey')
    )
    op.create_table('server_image',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_image_pkey')
    )
    op.create_table('server_network',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='server_network_pkey')
    )
    # ### end Alembic commands ###
